import Head from 'next/head';
import { FC } from 'react';
import RegistersTables from '@/components/Index/RegistersTable/RegistersTables';

const HomePage: FC = () => {
  return (
    <>
      <Head>
        <title>Gambit Labs Modbus project</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <main className='main'>
        <RegistersTables />
      </main>
    </>
  );
};

export default HomePage;
