import Head from 'next/head';
import { FC, useState } from 'react';

const HomePage: FC = () => {
  const [isLoading, setIsLoading] = useState<boolean>(true);

  if (!isLoading) {
    return <h2>Wait a little bit. Data are loading ...</h2>;
  }

  return (
    <>
      <Head>
        <title>Gambit Labs Modbus project</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <main className='main'>Main</main>
    </>
  );
};

export default HomePage;
